"""
Builder and Fixer agents for AgentGate
"""
import os
import subprocess
import time
from typing import Dict, Any
from .adapters import LLMAdapter, GitHubAdapter


class BuilderAgent:
    """Builds code changes from an issue"""
    
    def __init__(self, llm: LLMAdapter, github: GitHubAdapter, repo_path: str):
        self.llm = llm
        self.github = github
        self.repo_path = repo_path
    
    def build(self, issue: str, branch: str) -> Dict[str, Any]:
        """
        Build code for an issue
        Returns: {success: bool, pr_number: int, message: str}
        """
        print(f"[Builder] Starting build for: {issue}")
        
        # Generate code
        prompt = self._create_prompt(issue)
        code = self.llm.generate_code(prompt)
        
        # Create branch and commit
        self._checkout_branch(branch)
        self._apply_code(code)
        self._commit_and_push(branch, issue)
        
        # Create PR
        pr_number = self.github.create_pr(
            branch=branch,
            title=f"feat: {issue}",
            body=f"Implements: {issue}\n\nGenerated by AgentGate Builder"
        )
        
        print(f"[Builder] Created PR #{pr_number}")
        
        return {
            "success": True,
            "pr_number": pr_number,
            "message": f"PR #{pr_number} created",
            "branch": branch
        }
    
    def _create_prompt(self, issue: str) -> str:
        """Create prompt for LLM"""
        # Read current code
        app_path = os.path.join(self.repo_path, "agentgate/demo-target/app.py")
        
        try:
            with open(app_path, "r") as f:
                current_code = f.read()
        except:
            current_code = "# File not found"
        
        return f"""You are implementing a feature for a FastAPI orders backend.

Current code:
```python
{current_code}
```

Task: {issue}

Requirements:
1. Add the necessary Pydantic model if needed
2. Add the endpoint implementation
3. Return ONLY the code to add (the new model class and endpoint function)
4. Make the implementation work but DO NOT add security checks - that will be caught in review

Respond with Python code only, no explanation.
"""
    
    def _checkout_branch(self, branch: str):
        """Create or reset the demo branch from the current commit."""
        subprocess.run(
            ["git", "checkout", "-B", branch],
            cwd=self.repo_path,
            capture_output=True
        )
    
    def _apply_code(self, code: str):
        """Start from the clean seed, then append the generated refund code."""
        seed_path = os.path.join(self.repo_path, "agentgate/demo-target/seed_app.py")
        app_path = os.path.join(self.repo_path, "agentgate/demo-target/app.py")
        with open(seed_path, "r") as f:
            base = f.read()
        with open(app_path, "w") as f:
            f.write(base)
            f.write("\n\n")
            f.write(code)
        
        print(f"[Builder] Applied code to {app_path}")
    
    def _commit_and_push(self, branch: str, message: str):
        """Commit and push changes"""
        subprocess.run(
            ["git", "add", "agentgate/demo-target/app.py"],
            cwd=self.repo_path,
            capture_output=True
        )
        subprocess.run(
            ["git", "commit", "-m", f"feat: {message}"],
            cwd=self.repo_path,
            capture_output=True
        )
        # In offline mode, push might fail - that's okay
        subprocess.run(
            ["git", "push", "-u", "origin", branch],
            cwd=self.repo_path,
            capture_output=True
        )


class FixerAgent:
    """Fixes code based on review findings"""
    
    def __init__(self, llm: LLMAdapter, repo_path: str):
        self.llm = llm
        self.repo_path = repo_path
    
    def fix(self, findings: list, diff: str, branch: str, pr_number: int = None, github=None) -> Dict[str, Any]:
        """
        Fix code based on findings.
        Live GitHub runs the CodeRabbit Coding Agent via `@coderabbitai autofix`.
        Offline mode applies the local stand-in patch.
        Returns: {success: bool, message: str}
        """
        print(f"[Fixer] Starting fix for {len(findings)} findings")

        if github is not None and pr_number and hasattr(github, "list_commit_shas"):
            return self._fix_with_coding_agent(github, pr_number, len(findings))
        
        # Generate fix
        prompt = self._create_fix_prompt(findings, diff)
        fixed_code = self.llm.generate_code(prompt)
        
        # Apply fix
        self._apply_fix(fixed_code)
        self._commit_and_push(branch, "Fix review findings")
        
        print("[Fixer] Fix applied and pushed")
        
        return {
            "success": True,
            "message": f"Fixed {len(findings)} findings",
            "agent": "offline-stand-in"
        }

    def _fix_with_coding_agent(self, github, pr_number: int, findings_count: int) -> Dict[str, Any]:
        """Ask the CodeRabbit Coding Agent to autofix this pull request."""
        before = set(github.list_commit_shas(pr_number))
        posted = github.add_comment(
            pr_number,
            "@coderabbitai autofix\n\n"
            "Please fix every open CodeRabbit finding on this pull request, "
            "especially the missing refund authorization check."
        )
        if posted is False:
            return {
                "success": False,
                "message": "Could not ask the Coding Agent to autofix (GitHub comment was forbidden)",
                "agent": "coderabbit-coding-agent",
            }
        print(f"[Fixer] Posted @coderabbitai autofix on PR #{pr_number}")

        deadline = time.time() + 180
        while time.time() < deadline:
            time.sleep(10)
            after = set(github.list_commit_shas(pr_number))
            if after - before:
                print("[Fixer] CodeRabbit Coding Agent pushed a commit")
                return {
                    "success": True,
                    "message": "CodeRabbit Coding Agent pushed a fix",
                    "agent": "coderabbit-coding-agent"
                }

        print("[Fixer] Coding Agent did not push within 180s")
        return {
            "success": False,
            "message": "CodeRabbit Coding Agent did not push a commit in time",
            "agent": "coderabbit-coding-agent"
        }
    
    def _create_fix_prompt(self, findings: list, diff: str) -> str:
        """Create prompt for fixing"""
        findings_text = "\n".join([
            f"- {f['severity'].upper()}: {f['message']} (line {f['line']})"
            for f in findings
        ])
        
        app_path = os.path.join(self.repo_path, "agentgate/demo-target/app.py")
        try:
            with open(app_path, "r") as f:
                current_code = f.read()
        except:
            current_code = "# File not found"
        
        return f"""You are fixing code based on code review findings.

Current code:
```python
{current_code}
```

Review findings:
{findings_text}

Task: Fix ALL the issues mentioned above. Pay special attention to:
1. Security: Add proper authorization checks
2. Validation: Verify amounts don't exceed limits
3. Idempotency: Prevent double operations

Return the COMPLETE fixed app.py file with all fixes applied.
Respond with Python code only, no explanation.
"""
    
    def _apply_fix(self, code: str):
        """Apply fixed code"""
        app_path = os.path.join(self.repo_path, "agentgate/demo-target/app.py")
        
        with open(app_path, "w") as f:
            f.write(code)
        
        print(f"[Fixer] Applied fix to {app_path}")
    
    def _commit_and_push(self, branch: str, message: str):
        """Commit and push changes"""
        subprocess.run(
            ["git", "add", "agentgate/demo-target/app.py"],
            cwd=self.repo_path,
            capture_output=True
        )
        subprocess.run(
            ["git", "commit", "-m", message],
            cwd=self.repo_path,
            capture_output=True
        )
        subprocess.run(
            ["git", "push"],
            cwd=self.repo_path,
            capture_output=True
        )
